#!/usr/bin/env python3

import sys
import argparse
import lib.helpers.dev as dev
from lib.helpers.logger import start

if '+V' in sys.argv:
    print('Logging even before parsing arguments')
    debug = True
else:
    debug = False

help_mode = False

if '~h' in sys.argv or '~~help' in sys.argv:
    help_mode = True

log = start('InsPyPong', debug)
log.debug('Logger started')

parser = argparse.ArgumentParser(
    prog='InsPyPong',

    description='InsPyPong (by Inspyre Softworks) is just as it seems; our version of the Atari hit; Pong',
    epilog='Enjoy your game session',
    add_help=True,
    allow_abbrev=True,
    prefix_chars='~+'
    )

dev_unlocked = False

if dev.check():
    if help_mode:
        log.debug('Adding dev-mode to list of arguments')

    parser.add_argument(
        '+dev', '++dev-mode',
        action='store_true',
        help='Super-Duper Dev Mode',
        dest='dev_mode',
        default=False)

    dev_unlocked = True

# Assign arguments that will set attributes for player 1
parser.add_argument(
    '~p1', '~~player1-name',
    required=False,
    action='store',
    default='Player One',
    dest='p1',
    help='Specify a name for player one from the command-line. One white-space is allowed in this '
         'argument'
    )

parser.add_argument(
    '~p1c', '~~player1-paddle-color',
    required=False,
    action='store',
    default='red',
    dest='p1_paddle_color',
    help='Designate the color you\'d like the Player One paddle to be',
    )

# Asssign arguments that will set attributes for player 2
parser.add_argument(
    '~p2', '~~player2-name',
    required=False,
    action='store',
    default='Player Two',
    dest='p2',
    help='Specify a name for player two from the command-line. One white-space is allowed in this '
         'argument'
    )

parser.add_argument(
    '~p2c', '~~player2-paddle-color',
    required=False,
    action='store',
    default='blue',
    dest='p2_paddle_color',
    help='Designate the color you\'d like the Player Two paddle to be',
    )

# Assign arguments that will allow changing of log output verbosity
parser.add_argument(
    '+v', '~~verbose',
    required=False,
    action='store_true',
    default=False,
    dest='verbose',
    help='Program will output all information that it finds might be useful to the end-user(s)'
    )

parser.add_argument(
    '+D', '~~debug',
    required=False,
    action='store_true',
    default=False,
    dest='debug',
    help='Program will output all logs. (This data is essentially useless to non-developers or non-curious)'
    )

parser.add_argument(
    '+q', '~~quiet',
    required=False,
    action='store_true',
    default=True,
    dest='quiet',
    help='Program will suppress all logs that are not of level WARNING and above.'
    )

# This shouldn't be confused with +v (the verbose shortcode)
parser.add_argument(
    '~v', '~~version',
    action='version',
    version='rc1.6.3',
    help='Prints the full version of the program and exits.'
    )

# ToDo:
#     Assign arguments that will set attributes for the Ball
#     Assign arguments that will set attributes for the playing field/screen
#     Assign arguments that will redirect logging output (maybe)

args = parser.parse_args()

# If we're in dev-mode, print the dev-mode banner
if dev_unlocked:
    if args.dev_mode:
        dev.print_banner()
        dev_mode = True

# If we're in dev-mode, print the dev-mode banner


log.debug(f'My runtime configuration is: {args}')

from lib.pong.gui.start_screen import StartScreen

StartScreen(args.p1, args.p1_paddle_color, args.p2, args.p2_paddle_color, dev_mode=dev_mode)
